{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "this-app.serviceAccountName" . }}
  namespace: {{ include "this-app.namespace" . }}
  labels:
{{ include "this-app.labels" . | indent 4 }}
{{- end -}}
