apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-business-system-frontend
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rps.limit }}" # rps：每秒多少请求 超过之后就报错 https status: 503
spec:
  ingressClassName: class-443
  rules:
    - http:
        paths:
          - backend:
              service:
                name: business-system-frontend
                port:
                  number: 80
            path: /business-system-frontend
            pathType: ImplementationSpecific
