apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-model-manager-web
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rps.limit }}" # rps：每秒多少请求 超过之后就报错 https status: 503
spec:
  ingressClassName: class-443
  rules:
    - http:
        paths:
          - backend:
              service:
                name: mf-model-manager-nginx
                port:
                  number: 80
            path: /mf-model-manager
            pathType: ImplementationSpecific
          - backend:
              service:
                name: mf-model-manager
                port:
                  number: 9898
            path: /api/mf-model-manager
            pathType: Prefix
          - backend:
              service:
                name: mf-model-api
                port:
                  number: 9898
            path: /api/mf-model-api
            pathType: Prefix
