apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-aievla-web
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "{{ .Values.ingress.rps.limit }}" # rps：每秒多少请求 超过之后就报错 https status: 503
spec:
  ingressClassName: class-443
  rules:
    - http:
        paths:
          - backend:
              service:
                name: mf-aievla-nginx
                port:
                  number: 80
            path: /aievla
            pathType: ImplementationSpecific
          - backend:
              service:
                name: mf-dataset-manager
                port:
                  number: 6478
            path: /api/dataset-manager
            pathType: Prefix
          - backend:
              service:
                name: mf-benchmark-manager
                port:
                  number: 9899
            path: /api/benchmark-manager
            pathType: Prefix
          - backend:
              service:
                name: mf-aievla-task
                port:
                  number: 6483
            path: /api/mf-task
            pathType: Prefix
