{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  name: {{ include "template.serviceAccountName" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "template.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "template.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "template.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "template.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
rules:
  - apiGroups:
      - "*"
    resources:
      - '*'
    verbs:
      - "*"

{{- end }}
